/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/chair.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tapa004.geometry} material={materials.Fabric_01} />
      <mesh geometry={nodes.tapa004_1.geometry} material={materials.Fabric_02} />
      <mesh geometry={nodes.tapa004_2.geometry} material={materials.WoodLegs} />
      <mesh geometry={nodes.tapa004_3.geometry} material={materials.BlackPlastics} />
    </group>
  )
}

useGLTF.preload('/chair.glb')
